# **FACTORY TO CUSTOMER SHIPPING ROUTE EFFICIENCY ANALYSIS**
> Siya Pangam

## INTRODUCTION

In modern supply chain operations, efficient shipping is critical to maintaining customer satisfaction and controlling logistics costs. However, many organizations lack clear visibility into how their factory-to-customer delivery routes perform over time. This results in reactive decision-making, where delays and inefficiencies are addressed only after they occur rather than being proactively managed.

This project focuses on analyzing shipping data to uncover patterns in delivery performance across different routes, regions, and shipping modes. By quantifying lead times, identifying delay-prone routes, and evaluating geographic bottlenecks, the analysis aims to transform raw logistics data into actionable insights. The ultimate goal is to enable data-driven optimization of shipping operations and improve overall route efficiency.

## ANALYTICAL FRAMEWORK

This analysis follows a structured, KPI-driven approach to evaluate factory-to-customer shipping efficiency and identify operational bottlenecks.

* Data Validation & Cleaning: Ensure data integrity by standardizing date formats, removing invalid lead times, and handling missing records.

* Feature Engineering: Derive key variables such as Shipping Lead Time, route definitions (factory → region/state), and delay indicators.

* Route-Level Aggregation: Compute core metrics for each route, including shipment volume, average lead time, and variability.

* Performance Benchmarking: Rank routes to identify top-performing and underperforming corridors, and compare efficiency across ship modes.

* Geographic Analysis: Detect regions and states with high delays and congestion patterns.

* Operational Insights: Evaluate shipping modes and uncover cost–time trade-offs to support data-driven logistics optimization.

* Cross-Level Analysis: To check consistency translates from a higher route level to lower route levels.

This framework enables a transition from reactive monitoring to proactive, insight-driven decision-making in supply chain operations.

## EXPLORATORY DATA ANALYSIS

### Data Cleaning and Validation
Before analysis, validate the dataset to ensure accuracy, consistency, and reliability. This step focuses on correcting data types, handling missing values, and removing invalid records that could distort shipping performance insights.

In [1]:
#Libraries
import pandas as pd
import numpy as np

In [2]:
#Load dataset
df = pd.read_csv(r'C:\Users\User\Desktop\GitHubFiles\Factory to Customer Shipping Route Analysis\Data\Nassau Candy Distributor.csv')

In [3]:
#Basic Overview
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,134468.961154,13.908537,3.791838,9.166451,4.742087
std,2942.898656,20231.483007,11.341020,2.228317,6.643740,5.061647
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,192314.000000,260.000000,14.000000,130.000000,130.000000

In [5]:
df.isna().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='object')

In [8]:
#Drop irrelevant columns
cols_to_drop = ['Row ID', 'Order ID', 'Customer ID', 'Postal Code','Product ID', 'Product Name']
df_filtered = df.copy()
df_filtered = df_filtered.drop(columns=cols_to_drop)
df_filtered.columns

Index(['Order Date', 'Ship Date', 'Ship Mode', 'Country/Region', 'City',
       'State/Province', 'Division', 'Region', 'Sales', 'Units',
       'Gross Profit', 'Cost'],
      dtype='object')

In [9]:
#Converting date columns
df_filtered['Order Date'] = pd.to_datetime(df_filtered['Order Date'], format='%d-%m-%Y')
df_filtered['Ship Date'] = pd.to_datetime(df_filtered['Ship Date'], format='%d-%m-%Y')

In [10]:
#Standardizing Geographic Fields
df_filtered['Country/Region'] = df_filtered['Country/Region'].astype(str).str.upper().str.title()
df_filtered['Region'] = df_filtered['Region'].astype(str).str.upper().str.title()
df_filtered['State/Province'] = df_filtered['State/Province'].astype(str).str.upper().str.title()
df_filtered['City'] = df_filtered['City'].astype(str).str.upper().str.title()

In [11]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order Date      10194 non-null  datetime64[ns]
 1   Ship Date       10194 non-null  datetime64[ns]
 2   Ship Mode       10194 non-null  object
 3   Country/Region  10194 non-null  object
 4   City            10194 non-null  object
 5   State/Province  10194 non-null  object
 6   Division        10194 non-null  object
 7   Region          10194 non-null  object
 8   Sales           10194 non-null  float64
 9   Units           10194 non-null  int64
 10  Gross Profit    10194 non-null  float64
 11  Cost            10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(1), object(6)
memory usage: 955.8+ KB

In [12]:
df_filtered.groupby('State/Province')['City'].nunique().sort_values(ascending=False).head()

State/Province
California    81
Texas         54
Florida       36
Illinois      33
Ohio          24
Name: City, dtype: int64

## FEATURE ENGINEERING

In [13]:
#Defining Routes - Country Level
df_filtered['Route__Country'] = df_filtered['Country/Region']

In [14]:
#Defining Routes - Region Level
df_filtered['Route__Region'] = df_filtered['Country/Region'] + ' → ' + df_filtered['Region']

In [15]:
#Defining Routes- State Level
df_filtered['Route__State'] = df_filtered['Country/Region'] + ' → ' + df_filtered['Region'] + ' → ' + df_filtered['State/Province']

In [16]:
#Defining Routes - City Level
df_filtered['Route__City'] = df_filtered['Country/Region'] + ' → ' + df_filtered['Region'] + ' → ' + df_filtered['State/Province'] + ' → ' + df_filtered['City']

In [17]:
#Standardize ship-mode values
df_filtered['Ship Mode'] = df_filtered['Ship Mode'].str.strip().str.title()
#check unique categories
df_filtered['Ship Mode'].unique()

array(['Standard Class', 'First Class', 'Second Class', 'Same Day'],
      dtype=object)

####EDA_CHECKING FOR UNIQUE ROUTES

In [18]:
df_filtered.groupby('Route__Country').size().head()

Route__Country
Canada            200
United States    9994
dtype: int64

In [19]:
df_filtered.groupby('Route__Region').size().head()

Route__Region
Canada → Atlantic            138
Canada → Interior             12
Canada → Pacific              50
United States → Atlantic    2848
United States → Gulf        1620
dtype: int64

In [20]:
df_filtered.groupby('Route__State').size().head()

Route__State
Canada → Atlantic → New Brunswick                 8
Canada → Atlantic → Newfoundland And Labrador     6
Canada → Atlantic → Nova Scotia                   6
Canada → Atlantic → Ontario                      58
Canada → Atlantic → Prince Edward Island         10
dtype: int64

In [21]:
df_filtered.groupby('Route__City').size().head()

Route__City
Canada → Atlantic → New Brunswick → Moncton                    8
Canada → Atlantic → Newfoundland And Labrador → St. John'S     6
Canada → Atlantic → Nova Scotia → Halifax                      6
Canada → Atlantic → Ontario → Toronto                         58
Canada → Atlantic → Prince Edward Island → Charlottetown      10
dtype: int64

At the country level, the dataset is skewed, and each state/province is associated with only a single city. Therefore, analysis is conducted at the region and state levels to ensure more meaningful and reliable insights.

##KPI COMPUTATION
KPIs at route level- These metrics quantify delivery speed, reliability, and operational efficiency, enabling comparison across routes and shipping modes.

###Shipping Lead Time

In [22]:
#Calculating Shipping Lead time
df_filtered['Shipping Lead Time'] = (df_filtered['Ship Date'] - df_filtered['Order Date']).dt.days

###Route-Level Aggregation : Average Lead Time & Route Volume

In [23]:
#region level aggregation
route_agg_region = df_filtered.groupby('Route__Region').agg(Route_Volume = ('Shipping Lead Time', 'count'),Avg_Lead_Time=('Shipping Lead Time', 'mean'),Lead_Time_Variability=('Shipping Lead Time', 'std')).reset_index()
route_agg_region.head()

,Route__Region,Route_Volume,Avg_Lead_Time,Lead_Time_Variability
0,Canada → Atlantic,138,1275.992754,291.093195
1,Canada → Interior,12,1455.333333,191.139803
2,Canada → Pacific,50,1288.540000,295.004131
3,United States → Atlantic,2848,1325.010534,254.588321
4,United States → Gulf,1620,1311.374691,264.727855

In [24]:
#State level aggregation
route_agg_state = df_filtered.groupby('Route__State').agg(Route_Volume = ('Shipping Lead Time', 'count'), Avg_Lead_Time=('Shipping Lead Time', 'mean'),Lead_Time_Variability=('Shipping Lead Time', 'std')).reset_index()
route_agg_state.head()

,Route__State,Route_Volume,Avg_Lead_Time,Lead_Time_Variability
0,Canada → Atlantic → New Brunswick,8,1273.250000,276.292159
1,Canada → Atlantic → Newfoundland And Labrador,6,1216.166667,357.447292
2,Canada → Atlantic → Nova Scotia,6,1272.666667,326.914464
3,Canada → Atlantic → Ontario,58,1247.465517,272.269939
4,Canada → Atlantic → Prince Edward Island,10,1420.300000,255.814190

###Delay Frequency

In [25]:
#Delay Threshold
df_filtered['Shipping Lead Time'].describe()

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Shipping Lead Time, dtype: float64

In [26]:
#Top 25% slowest shipments = delayed
Delay_threshold_region= df_filtered.groupby('Route__Region')['Shipping Lead Time'].quantile(0.75)
Delay_threshold_state= df_filtered.groupby('Route__State')['Shipping Lead Time'].quantile(0.75)

In [27]:
df_filtered['Is_Delayed_region'] = df_filtered['Shipping Lead Time'] > df_filtered['Route__Region'].map(Delay_threshold_region)
df_filtered['Is_Delayed_state']= df_filtered['Shipping Lead Time'] > df_filtered['Route__State'].map(Delay_threshold_state)

In [28]:
#Delay-Region Level
delay_region = df_filtered.groupby('Route__Region')['Is_Delayed_region'].mean().reset_index()
delay_region.rename(columns={'Is_Delayed_region': 'Delay_Frequency_RegionLevel'}, inplace=True)
delay_region['Delay_Frequency_RegionLevel'] = delay_region['Delay_Frequency_RegionLevel'] * 100

In [29]:
#Delay-State Level
delay_state = df_filtered.groupby('Route__State')['Is_Delayed_state'].mean().reset_index()
delay_state.rename(columns={'Is_Delayed_state': 'Delay_Frequency_StateLevel'}, inplace=True)
delay_state['Delay_Frequency_StateLevel'] = delay_state['Delay_Frequency_StateLevel'] * 100

###Route Efficiency score

In [30]:
#Region Level
region_avg = df_filtered.groupby('Route__Region')['Shipping Lead Time'].mean().reset_index()
region_avg['Normalized_Lead_Time']= ((region_avg['Shipping Lead Time'] - region_avg['Shipping Lead Time'].min()) / (region_avg['Shipping Lead Time'].max() - region_avg['Shipping Lead Time'].min()))
region_avg['Route_Efficiency_Score'] = 1 - region_avg['Normalized_Lead_Time']

In [31]:
#State Level
state_avg = df_filtered.groupby('Route__State')['Shipping Lead Time'].mean().reset_index()
state_avg['Normalized_Lead_Time']= ((state_avg['Shipping Lead Time'] - state_avg['Shipping Lead Time'].min()) / (state_avg['Shipping Lead Time'].max() - state_avg['Shipping Lead Time'].min()))
state_avg['Route_Efficiency_Score'] = 1 - state_avg['Normalized_Lead_Time']

###KPI Table Construction

In [32]:
#Region Level
Region_KPI_table = pd.merge(route_agg_region, delay_region, on='Route__Region', how='left')
Region_KPI_table = pd.merge(Region_KPI_table, region_avg, on='Route__Region', how='left')
Region_KPI_table = Region_KPI_table.drop(columns=['Shipping Lead Time'])
Region_KPI_table.head()

,Route__Region,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_RegionLevel,Normalized_Lead_Time,Route_Efficiency_Score
0,Canada → Atlantic,138,1275.992754,291.093195,22.463768,0.000000,1.000000
1,Canada → Interior,12,1455.333333,191.139803,0.000000,1.000000,0.000000
2,Canada → Pacific,50,1288.540000,295.004131,24.000000,0.069963,0.930037
3,United States → Atlantic,2848,1325.010534,254.588321,24.929775,0.273322,0.726678
4,United States → Gulf,1620,1311.374691,264.727855,20.493827,0.197289,0.802711

In [33]:
#State Level
State_KPI_table = pd.merge(route_agg_state, delay_state, on='Route__State', how='left')
State_KPI_table = pd.merge(State_KPI_table, state_avg, on='Route__State', how='left')
State_KPI_table = State_KPI_table.drop(columns=['Shipping Lead Time'])
State_KPI_table.head()

,Route__State,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
0,Canada → Atlantic → New Brunswick,8,1273.250000,276.292159,25.000000,0.271774,0.728226
1,Canada → Atlantic → Newfoundland And Labrador,6,1216.166667,357.447292,33.333333,0.157807,0.842193
2,Canada → Atlantic → Nova Scotia,6,1272.666667,326.914464,33.333333,0.270610,0.729390
3,Canada → Atlantic → Ontario,58,1247.465517,272.269939,24.137931,0.220296,0.779704
4,Canada → Atlantic → Prince Edward Island,10,1420.300000,255.814190,0.000000,0.565361,0.434639

##Efficiency Benchmarking
Benchmarking shipping routes based on delivery performance to identify the most and least efficient routes.

In [34]:
#Region level - Efficiency score
Top_Efficient_Region = Region_KPI_table.sort_values(by='Route_Efficiency_Score', ascending=False).head(10)
Top_Efficient_Region

,Route__Region,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_RegionLevel,Normalized_Lead_Time,Route_Efficiency_Score
0,Canada → Atlantic,138,1275.992754,291.093195,22.463768,0.000000,1.000000
2,Canada → Pacific,50,1288.540000,295.004131,24.000000,0.069963,0.930037
4,United States → Gulf,1620,1311.374691,264.727855,20.493827,0.197289,0.802711
5,United States → Interior,2323,1322.408093,262.870002,21.437796,0.258811,0.741189
6,United States → Pacific,3203,1322.720262,266.018144,21.011552,0.260552,0.739448
3,United States → Atlantic,2848,1325.010534,254.588321,24.929775,0.273322,0.726678
1,Canada → Interior,12,1455.333333,191.139803,0.000000,1.000000,0.000000

In [35]:
#State level - Efficieny Score - TOP 10
Top_Efficient_State = State_KPI_table.sort_values(by='Route_Efficiency_Score', ascending=False).head(10)
Top_Efficient_State

,Route__State,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
13,United States → Atlantic → Maine,8,1137.125000,189.733977,0.000000,0.000000,1.000000
1,Canada → Atlantic → Newfoundland And Labrador,6,1216.166667,357.447292,33.333333,0.157807,0.842193
53,United States → Pacific → Nevada,39,1226.794872,239.772390,23.076923,0.179026,0.820974
34,United States → Gulf → Virginia,224,1229.125000,256.420396,19.642857,0.183679,0.816321
3,Canada → Atlantic → Ontario,58,1247.465517,272.269939,24.137931,0.220296,0.779704
56,United States → Pacific → Utah,53,1253.000000,289.780554,24.528302,0.231345,0.768655
32,United States → Gulf → South Carolina,42,1255.428571,241.749835,19.047619,0.236194,0.763806
29,United States → Gulf → Louisiana,42,1263.785714,306.777550,19.047619,0.252879,0.747121
30,United States → Gulf → Mississippi,53,1266.566038,263.148869,24.528302,0.258430,0.741570
55,United States → Pacific → Oregon,124,1267.709677,259.367642,24.193548,0.260713,0.739287

In [36]:
#State level - Efficieny Score - BOTTOM 10
Bottom_Efficient_State = State_KPI_table.sort_values(by='Route_Efficiency_Score', ascending=False).tail(10)
Bottom_Efficient_State

,Route__State,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
33,United States → Gulf → Tennessee,183,1391.486339,248.201971,20.765027,0.507834,0.492166
45,United States → Interior → South Dakota,12,1395.916667,360.350955,8.333333,0.516679,0.483321
4,Canada → Atlantic → Prince Edward Island,10,1420.300000,255.814190,0.000000,0.565361,0.434639
22,United States → Atlantic → Vermont,11,1438.909091,190.999714,9.090909,0.602514,0.397486
54,United States → Pacific → New Mexico,37,1441.837838,267.198066,10.810811,0.608361,0.391639
37,United States → Interior → Iowa,30,1443.900000,229.801466,10.000000,0.612478,0.387522
6,Canada → Interior → Manitoba,12,1455.333333,191.139803,0.000000,0.635305,0.364695
9,Canada → Pacific → Saskatchewan,2,1457.000000,258.801082,50.000000,0.638632,0.361368
43,United States → Interior → North Dakota,7,1637.857143,1.463850,28.571429,0.999715,0.000285
23,United States → Atlantic → West Virginia,4,1638.000000,2.000000,0.000000,1.000000,0.000000

###Comparing Performance across ship modes

In [37]:
#Average lead time by Ship mode
Ship_mode_perf = df_filtered.groupby('Ship Mode')['Shipping Lead Time'].mean().reset_index()
Ship_mode_perf.rename(columns={'Shipping Lead Time': 'Avg_Lead_Time'}, inplace=True)
Ship_mode_perf

        Ship Mode  Avg_Lead_Time
0     First Class    1338.275840
1        Same Day    1333.442413
2    Second Class    1323.845376
3  Standard Class    1314.334641

In [38]:
#Delay frequency by Ship mode - Region level
Ship_mode_delay_region = df_filtered.groupby('Ship Mode')['Is_Delayed_region'].mean().reset_index()
Ship_mode_delay_region['Delay_Freq_Region'] = Ship_mode_delay_region['Is_Delayed_region'] * 100
Ship_mode_delay_region = Ship_mode_delay_region.drop(columns=['Is_Delayed_region'])
Ship_mode_delay_region

        Ship Mode  Delay_Freq_Region
0     First Class           3.746770
1        Same Day           0.000000
2    Second Class          15.209702
3  Standard Class          30.996732

In [39]:
#Delay frequency by Ship mode - State level
Ship_mode_delay_state = df_filtered.groupby('Ship Mode')['Is_Delayed_state'].mean().reset_index()
Ship_mode_delay_state['Delay_Freq_State'] = Ship_mode_delay_state['Is_Delayed_state'] * 100
Ship_mode_delay_state = Ship_mode_delay_state.drop(columns=['Is_Delayed_state'])
Ship_mode_delay_state

        Ship Mode  Delay_Freq_State
0     First Class          8.139535
1        Same Day          2.376600
2    Second Class         17.534108
3  Standard Class         29.705882

##Geographic Bottleneck Analysis
Identifing regions and states with consistently poor shipping performance. This includes detecting areas with high delivery times, high shipment loads combined with delays, and congestion-prone routes.

In [40]:
#Region level- Average lead time
High_Lead_Time_Region = Region_KPI_table.sort_values(by='Avg_Lead_Time', ascending=False).head(10)
High_Lead_Time_Region

,Route__Region,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_RegionLevel,Normalized_Lead_Time,Route_Efficiency_Score
1,Canada → Interior,12,1455.333333,191.139803,0.000000,1.000000,0.000000
3,United States → Atlantic,2848,1325.010534,254.588321,24.929775,0.273322,0.726678
6,United States → Pacific,3203,1322.720262,266.018144,21.011552,0.260552,0.739448
5,United States → Interior,2323,1322.408093,262.870002,21.437796,0.258811,0.741189
4,United States → Gulf,1620,1311.374691,264.727855,20.493827,0.197289,0.802711
2,Canada → Pacific,50,1288.540000,295.004131,24.000000,0.069963,0.930037
0,Canada → Atlantic,138,1275.992754,291.093195,22.463768,0.000000,1.000000

In [41]:
#State level - Average lead time - TOP 10
High_Lead_Time_State = State_KPI_table.sort_values(by='Avg_Lead_Time', ascending=False).head(10)
High_Lead_Time_State

,Route__State,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
23,United States → Atlantic → West Virginia,4,1638.000000,2.000000,0.000000,1.000000,0.000000
43,United States → Interior → North Dakota,7,1637.857143,1.463850,28.571429,0.999715,0.000285
9,Canada → Pacific → Saskatchewan,2,1457.000000,258.801082,50.000000,0.638632,0.361368
6,Canada → Interior → Manitoba,12,1455.333333,191.139803,0.000000,0.635305,0.364695
37,United States → Interior → Iowa,30,1443.900000,229.801466,10.000000,0.612478,0.387522
54,United States → Pacific → New Mexico,37,1441.837838,267.198066,10.810811,0.608361,0.391639
22,United States → Atlantic → Vermont,11,1438.909091,190.999714,9.090909,0.602514,0.397486
4,Canada → Atlantic → Prince Edward Island,10,1420.300000,255.814190,0.000000,0.565361,0.434639
45,United States → Interior → South Dakota,12,1395.916667,360.350955,8.333333,0.516679,0.483321
33,United States → Gulf → Tennessee,183,1391.486339,248.201971,20.765027,0.507834,0.492166

In [42]:
#State level - Average lead time - BOTTOM 10
Low_Lead_Time_State = State_KPI_table.sort_values(by='Avg_Lead_Time', ascending=False).tail(10)
Low_Lead_Time_State

,Route__State,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
55,United States → Pacific → Oregon,124,1267.709677,259.367642,24.193548,0.260713,0.739287
30,United States → Gulf → Mississippi,53,1266.566038,263.148869,24.528302,0.258430,0.741570
29,United States → Gulf → Louisiana,42,1263.785714,306.777550,19.047619,0.252879,0.747121
32,United States → Gulf → South Carolina,42,1255.428571,241.749835,19.047619,0.236194,0.763806
56,United States → Pacific → Utah,53,1253.000000,289.780554,24.528302,0.231345,0.768655
3,Canada → Atlantic → Ontario,58,1247.465517,272.269939,24.137931,0.220296,0.779704
34,United States → Gulf → Virginia,224,1229.125000,256.420396,19.642857,0.183679,0.816321
53,United States → Pacific → Nevada,39,1226.794872,239.772390,23.076923,0.179026,0.820974
1,Canada → Atlantic → Newfoundland And Labrador,6,1216.166667,357.447292,33.333333,0.157807,0.842193
13,United States → Atlantic → Maine,8,1137.125000,189.733977,0.000000,0.000000,1.000000

###High Shipment Volume + Poor Performance (True Bottlenecks)

In [43]:
#Region level
Bottlenecks_region = Region_KPI_table[(Region_KPI_table['Route_Volume'] > Region_KPI_table['Route_Volume'].quantile(0.75)) & (Region_KPI_table['Delay_Frequency_RegionLevel'] > Region_KPI_table['Delay_Frequency_RegionLevel'].quantile(0.75))]
Bottlenecks_region

,Route__Region,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_RegionLevel,Normalized_Lead_Time,Route_Efficiency_Score
3,United States → Atlantic,2848,1325.010534,254.588321,24.929775,0.273322,0.726678

In [44]:
#State Level
Bottlenecks_state = State_KPI_table[(State_KPI_table['Route_Volume'] > State_KPI_table['Route_Volume'].quantile(0.75)) & (State_KPI_table['Delay_Frequency_StateLevel'] > State_KPI_table['Delay_Frequency_StateLevel'].quantile(0.75))]
Bottlenecks_state

,Route__State,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
18,United States → Atlantic → New York,1128,1324.493794,249.358503,24.911348,0.374083,0.625917
27,United States → Gulf → Georgia,184,1338.635870,249.182868,25.000000,0.402318,0.597682

###Congestion Prone

In [45]:
#Region Level
Congestion_region = Region_KPI_table.sort_values(by='Delay_Frequency_RegionLevel', ascending=False).head(10)
Congestion_region

,Route__Region,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_RegionLevel,Normalized_Lead_Time,Route_Efficiency_Score
3,United States → Atlantic,2848,1325.010534,254.588321,24.929775,0.273322,0.726678
2,Canada → Pacific,50,1288.540000,295.004131,24.000000,0.069963,0.930037
0,Canada → Atlantic,138,1275.992754,291.093195,22.463768,0.000000,1.000000
5,United States → Interior,2323,1322.408093,262.870002,21.437796,0.258811,0.741189
6,United States → Pacific,3203,1322.720262,266.018144,21.011552,0.260552,0.739448
4,United States → Gulf,1620,1311.374691,264.727855,20.493827,0.197289,0.802711
1,Canada → Interior,12,1455.333333,191.139803,0.000000,1.000000,0.000000

In [46]:
#State Level - High Congestion
Congestion_state_high = State_KPI_table.sort_values(by='Delay_Frequency_StateLevel', ascending=False).head(10)
Congestion_state_high

,Route__State,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
9,Canada → Pacific → Saskatchewan,2,1457.000000,258.801082,50.000000,0.638632,0.361368
2,Canada → Atlantic → Nova Scotia,6,1272.666667,326.914464,33.333333,0.270610,0.729390
1,Canada → Atlantic → Newfoundland And Labrador,6,1216.166667,357.447292,33.333333,0.157807,0.842193
43,United States → Interior → North Dakota,7,1637.857143,1.463850,28.571429,0.999715,0.000285
52,United States → Pacific → Montana,15,1273.800000,308.316906,26.666667,0.272872,0.727128
42,United States → Interior → Nebraska,38,1311.236842,237.213376,26.315789,0.347615,0.652385
16,United States → Atlantic → New Hampshire,27,1300.037037,247.406001,25.925926,0.325255,0.674745
41,United States → Interior → Missouri,66,1339.863636,278.414792,25.757576,0.404769,0.595231
44,United States → Interior → Oklahoma,66,1301.363636,241.757134,25.757576,0.327903,0.672097
25,United States → Gulf → Arkansas,60,1285.733333,284.746266,25.000000,0.296697,0.703303

In [47]:
#Statelevel - Low Congestion
Congestion_state_low = State_KPI_table.sort_values(by='Delay_Frequency_StateLevel', ascending= False).tail(10)
Congestion_state_low

,Route__State,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
54,United States → Pacific → New Mexico,37,1441.837838,267.198066,10.810811,0.608361,0.391639
37,United States → Interior → Iowa,30,1443.900000,229.801466,10.000000,0.612478,0.387522
22,United States → Atlantic → Vermont,11,1438.909091,190.999714,9.090909,0.602514,0.397486
45,United States → Interior → South Dakota,12,1395.916667,360.350955,8.333333,0.516679,0.483321
23,United States → Atlantic → West Virginia,4,1638.000000,2.000000,0.000000,1.000000,0.000000
7,Canada → Pacific → Alberta,26,1274.076923,292.400673,0.000000,0.273425,0.726575
4,Canada → Atlantic → Prince Edward Island,10,1420.300000,255.814190,0.000000,0.565361,0.434639
13,United States → Atlantic → Maine,8,1137.125000,189.733977,0.000000,0.000000,1.000000
6,Canada → Interior → Manitoba,12,1455.333333,191.139803,0.000000,0.635305,0.364695
58,United States → Pacific → Wyoming,1,1274.000000,NaN,0.000000,0.273272,0.726728

###Slow + Delayed (Worst Case Routes)

In [48]:
#Region Level
Worst_case_region = Region_KPI_table[(Region_KPI_table['Delay_Frequency_RegionLevel'] > Region_KPI_table['Delay_Frequency_RegionLevel'].quantile(0.75)) & (Region_KPI_table['Avg_Lead_Time'] > Region_KPI_table['Avg_Lead_Time'].quantile(0.75))]
Worst_case_region

,Route__Region,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_RegionLevel,Normalized_Lead_Time,Route_Efficiency_Score
3,United States → Atlantic,2848,1325.010534,254.588321,24.929775,0.273322,0.726678

In [49]:
#State Level
Worst_case_state = State_KPI_table[(State_KPI_table['Delay_Frequency_StateLevel'] > State_KPI_table['Delay_Frequency_StateLevel'].quantile(0.75)) & (State_KPI_table['Avg_Lead_Time'] > State_KPI_table['Avg_Lead_Time'].quantile(0.75))]
Worst_case_state

,Route__State,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
9,Canada → Pacific → Saskatchewan,2,1457.000000,258.801082,50.000000,0.638632,0.361368
43,United States → Interior → North Dakota,7,1637.857143,1.463850,28.571429,0.999715,0.000285

##Ship Mode Performance Analysis
Evaluating shipping performance across different ship modes to assess their impact on delivery speed, reliability, and cost.

In [50]:
#Average Lead time = Speed + Delay Frequency = Reliability

#Region Level
Ship_mode_analysis_Region = df_filtered.groupby('Ship Mode').agg(Avg_Lead_Time=('Shipping Lead Time', 'mean'),Delay_Frequency=('Is_Delayed_region', 'mean')).reset_index()
Ship_mode_analysis_Region

        Ship Mode  Avg_Lead_Time  Delay_Frequency
0     First Class    1338.275840         0.037468
1        Same Day    1333.442413         0.000000
2    Second Class    1323.845376         0.152097
3  Standard Class    1314.334641         0.309967

In [51]:
#Sate level
Ship_mode_analysis_State = df_filtered.groupby('Ship Mode').agg(Avg_Lead_Time=('Shipping Lead Time', 'mean'),Delay_Frequency=('Is_Delayed_state', 'mean')).reset_index()
Ship_mode_analysis_State

        Ship Mode  Avg_Lead_Time  Delay_Frequency
0     First Class    1338.275840         0.081395
1        Same Day    1333.442413         0.023766
2    Second Class    1323.845376         0.175341
3  Standard Class    1314.334641         0.297059

In [52]:
#Standard vs Expedited Comparison
df_filtered['ShipMode_group'] = df_filtered['Ship Mode'].replace({'Standard Class': 'Standard', 'Second Class': 'Standard', 'First Class' : 'Expedited' , 'Same Day' : 'Expedited'})

In [53]:
#Region Level
ShipMode_group_analysis_region = df_filtered.groupby('ShipMode_group').agg(Avg_Lead_Time=('Shipping Lead Time', 'mean'), Delay_Frequency=('Is_Delayed_region', 'mean')).reset_index()
ShipMode_group_analysis_region

  ShipMode_group  Avg_Lead_Time  Delay_Frequency
0      Expedited    1337.013842         0.027685
1       Standard    1316.658600         0.271392

In [54]:
#State Level
ShipMode_group_analysis_state = df_filtered.groupby('ShipMode_group').agg(Avg_Lead_Time=('Shipping Lead Time', 'mean'), Delay_Frequency=('Is_Delayed_state', 'mean')).reset_index()
ShipMode_group_analysis_state

  ShipMode_group  Avg_Lead_Time  Delay_Frequency
0      Expedited    1337.013842         0.066348
1       Standard    1316.658600         0.267317

In [55]:
#Cost vs Time trade off
cost_time_analysis = df_filtered.groupby('Ship Mode').agg(Average_Lead_time = ('Shipping Lead Time', 'mean'), Average_Cost = ('Cost', 'mean'), Average_Gross_Profit = ('Gross Profit', 'mean')).reset_index()
cost_time_analysis

        Ship Mode  Average_Lead_time  Average_Cost  Average_Gross_Profit
0     First Class        1338.275840      4.721124              9.051092
1        Same Day        1333.442413      4.411225              8.593656
2    Second Class        1323.845376      4.827539              9.250389
3  Standard Class        1314.334641      4.749328              9.219683

##Cross Level Performance Analysis
To check if performance at higher aggregation level translates to similar outcomes at more granular level.

In [56]:
#State Map -> Region
State_KPI_table['Region'] = State_KPI_table['Route__State'].str.split(' → ').str[1]


cols = State_KPI_table.columns.tolist()
cols.remove('Region')
cols.insert(1, 'Region')
State_KPI_table = State_KPI_table[cols]
State_KPI_table.head(3)

,Route__State,Region,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
0,Canada → Atlantic → New Brunswick,Atlantic,8,1273.250000,276.292159,25.000000,0.271774,0.728226
1,Canada → Atlantic → Newfoundland And Labrador,Atlantic,6,1216.166667,357.447292,33.333333,0.157807,0.842193
2,Canada → Atlantic → Nova Scotia,Atlantic,6,1272.666667,326.914464,33.333333,0.270610,0.729390

In [57]:
top_regions = Top_Efficient_Region['Route__Region'].str.split(' → ').str[1].head(3)
top_regions

0    Atlantic
2     Pacific
4        Gulf
Name: Route__Region, dtype: object

In [58]:
states_in_top_region= State_KPI_table[State_KPI_table['Region'].isin(top_regions)]
states_in_top_region.sort_values(by='Route_Efficiency_Score', ascending=False).head(5)

,Route__State,Region,Route_Volume,Avg_Lead_Time,Lead_Time_Variability,Delay_Frequency_StateLevel,Normalized_Lead_Time,Route_Efficiency_Score
13,United States → Atlantic → Maine,Atlantic,8,1137.125000,189.733977,0.000000,0.000000,1.000000
1,Canada → Atlantic → Newfoundland And Labrador,Atlantic,6,1216.166667,357.447292,33.333333,0.157807,0.842193
53,United States → Pacific → Nevada,Pacific,39,1226.794872,239.772390,23.076923,0.179026,0.820974
34,United States → Gulf → Virginia,Gulf,224,1229.125000,256.420396,19.642857,0.183679,0.816321
3,Canada → Atlantic → Ontario,Atlantic,58,1247.465517,272.269939,24.137931,0.220296,0.779704

In [59]:
#CHECKING FOR CONSISTENCY
State_KPI_table['High_performance'] = State_KPI_table['Route_Efficiency_Score'] > State_KPI_table['Route_Efficiency_Score'].quantile(0.75)
consistency_check = State_KPI_table.groupby('Region')['High_performance'].mean().reset_index()
consistency_check

     Region  High_performance
0  Atlantic          0.300000
1      Gulf          0.363636
2  Interior          0.071429
3   Pacific          0.285714

##KEY INSIGHTS:
The analysis of shipping performance across region and state levels reveals important patterns in efficiency, bottlenecks, and operational consistency.

> 🚀 High Performing Routes

At the regional level, Canada → Atlantic emerges as the most efficient region, while Canada → Interior shows the weakest performance.

At the state level, top-performing routes include:

- United States → Atlantic → Maine
- Canada → Atlantic → Newfoundland And Labrador
- United States → Pacific → Nevada

In contrast, the least efficient routes are:

- United States → Atlantic → West Virginia
- United States → Interior → North Dakota
- Canada → Pacific → Saskatchewan

These results highlight that while certain regions perform well overall, performance can vary significantly across individual states.


> 🚨 Bottleneck Routes (High Volume + Poor Performance)

Routes combining high shipment volume with poor performance are identified as critical bottlenecks.

- At the regional level, United States → Atlantic stands out as a major bottleneck
- At the state level, key bottlenecks include:

  United States → Gulf → Georgia

  United States → Atlantic → New York

These routes indicate areas where high operational load may be contributing to inefficiencies and delays.


> ⚠️ Congestion-Prone Routes

Congestion-prone areas are identified based on high delay frequency and unreliable performance.

At the regional level,
- United States → Atlantic , shows consistent signs of congestion

At the state level,

- Canada → Pacific → Saskatchewan , emerges as a key congestion-prone route

These regions may require operational optimization to improve reliability.


> ❌ Worst-Case Routes (Slow + Delayed)

Routes that are both slow and delay-prone represent the most critical performance issues.

At the regional level,
- United States → Atlantic is identified as the worst-performing region

At the state level, the most critical routes include:

- Canada → Pacific → Saskatchewan
- United States → Interior → North Dakota

These routes require immediate attention due to combined inefficiencies in speed and reliability.

> 🔍 Cross-Level Insights

Cross-level analysis reveals that strong regional performance does not always translate to consistent state-level outcomes.

At the regional level, the most efficient regions are:
Atlantic (top)
Followed by Pacific and Gulf
However, at the state level, while United States → Atlantic → Maine is the top-performing route, aggregated performance trends differ:
Gulf emerges as the most consistently high-performing region
Followed by Atlantic

This indicates that regional averages can mask variability at the state level, emphasizing the importance of multi-level analysis.

#App Requirements

#Saving KPI tables as csv files   
Region_KPI_table.to_csv(r'C:\Users\User\Desktop\GitHubFiles\Factory to Customer Shipping Route Analysis\Data\Region_KPI_table.csv', index=False)
State_KPI_table.to_csv(r'C:\Users\User\Desktop\GitHubFiles\Factory to Customer Shipping Route Analysis\Data\State_KPI_table.csv', index=False)

#Extracting Unique Countries, Regions and States for Abbrevations in visualizations
Countries = df_filtered['Country/Region'].unique()
Regions = df_filtered['Region'].unique()
States = df_filtered['State/Province'].unique()

Countries, Regions, States

from geopy.geocoders import Nominatim
import time

Country_mapping = {
    "United States": "USA", 
    "Canada": "CA"}
Region_mapping = {'Interior': 'INT', 'Atlantic': 'ATL', 'Gulf': 'GUL', 'Pacific': 'PAC'}
US_State_mapping = {"Alabama": "AL-USA", "Arkansas": "AR-USA", "Florida": "FL-USA", "Georgia": "GA-USA",
    "Kentucky": "KY-USA", "Louisiana": "LA-USA", "Mississippi": "MS-USA",
    "North Carolina": "NC-USA", "South Carolina": "SC-USA", "Tennessee": "TN-USA",
    "Virginia": "VA-USA", "West Virginia": "WV-USA", "Connecticut": "CT-USA",
    "Delaware": "DE-USA", "District Of Columbia": "DC-USA", "Maine": "ME-USA",
    "Maryland": "MD-USA", "Massachusetts": "MA-USA", "New Hampshire": "NH-USA",
    "New Jersey": "NJ-USA", "New York": "NY-USA", "Ohio": "OH-USA",
    "Pennsylvania": "PA-USA", "Rhode Island": "RI-USA", "Vermont": "VT-USA",
    "Illinois": "IL-USA", "Indiana": "IN-USA", "Iowa": "IA-USA", "Kansas": "KS-USA",
    "Michigan": "MI-USA", "Minnesota": "MN-USA", "Missouri": "MO-USA",
    "Nebraska": "NE-USA", "North Dakota": "ND-USA", "Oklahoma": "OK-USA",
    "South Dakota": "SD-USA", "Texas": "TX-USA", "Wisconsin": "WI-USA",
    "Arizona": "AZ-USA", "California": "CA-USA", "Colorado": "CO-USA",
    "Idaho":"ID-USA", "Montana":"MT-USA","Nevada":"NV-USA",
    "New Mexico":"NM-USA", "Oregon":"OR-USA","Utah":"UT-USA",
    "Washington":"WA-USA", "Wyoming":"WY-USA"}
Canada_State_mapping = {"Alberta": "AB-CA", "British Columbia": "BC-CA", "Manitoba": "MB-CA",
    "New Brunswick": "NB-CA", "Newfoundland And Labrador": "NL-CA",
    "Nova Scotia": "NS-CA", "Ontario": "ON-CA", "Prince Edward Island": "PE-CA",
    "Quebec": "QC-CA", "Saskatchewan": "SK-CA"}
State_Mapping = {**US_State_mapping, **Canada_State_mapping}
State_Mapping_df = pd.DataFrame(list(State_Mapping.items()), columns=['State/Province', 'State_Code'])
State_Mapping_df.to_csv(r'C:\Users\User\Desktop\GitHubFiles\Factory to Customer Shipping Route Analysis\Data\State_Mapping.csv', index=False)

geolocator = Nominatim(user_agent="geo_app")

State_Mapping_df['Country'] = State_Mapping_df['State_Code'].str.split('-').str[1].map({
    'USA': 'United States',
    'CA': 'Canada'
})

def get_coordinates(state_name, country):
    try:
        query = f"{state_name}, {country}"
        location = geolocator.geocode(query)
        if location:
            return location.latitude, location.longitude
    except:
        pass
    return None, None

coords = []

for _, row in State_Mapping_df.iterrows():
    lat, lon = get_coordinates(row['State/Province'], row['Country'])
    coords.append((lat, lon))
    time.sleep(1)

State_Mapping_df[['Lat', 'Lon']] = pd.DataFrame(coords, index=State_Mapping_df.index)

print(State_Mapping_df[State_Mapping_df['Lat'].isna()])

State_Mapping_df.to_csv("C:\\Users\\User\\Desktop\\GitHubFiles\\Factory to Customer Shipping Route Analysis\\Data\\state_mapping_with_coords.csv", index=False)

State_Mapping_df.head()